---
title: "Pivot Lobsters"
author: "Connor"
date: "1/27/2020"
output: html_document
---
Attaching our packages and reading in data

```{r setup}

library(tidyverse)
library(readxl)
library(here)
library(skimr)
library(kableExtra)

# read in lobster data

lobsters <- read_xlsx(here("data", "lobsters2.xlsx"), skip = 4)

```
Viewing our data with skimr
```{r}
skimr::skim(lobsters)
```
%>% is the pipe operator. This reads "and then"

### Pivot Tables
in R, Pivot Tables are `group_by() %>% summarize()`
'n' function will count observations

```{r Pivot Table dplyr}
lobsters %>% group_by(site, year) %>% summarize(count_by_site_year = n())

```

Summarize by multiple variables
```{r}
siteyear_summary <- (lobsters %>% group_by(site, year) %>% summarize(count_by_site_year = n(), mean_size_mm = mean(size_mm, na.rm = TRUE), sd_size_mm = sd(size_mm, na.rm = TRUE)))

```
Table formatting with `kableExtra::kable`
```{r}
siteyear_summary %>% kable()
```

There are `r nrow(lobsters)` total lobsters included in this report

```{r}
siteyear_median_summary <- (lobsters %>% group_by(site, year) %>% summarize(count_by_site_year = n(), median_size_mm = median(size_mm, na.rm = TRUE), sd_size_mm = sd(size_mm, na.rm = TRUE)))

ggplot(data = siteyear_median_summary, aes(x = year, y = median_size_mm, color = site)) + geom_line()

ggsave(here("figures", "lobsters-plot.png"))

```

